### ISSUE TITLE
Add option to add fog

### ISSUE THREAD

**Issue by kannes** [minorua/Qgis2threejs#105]
Adding simple, distance-based fog can greatly enhance the visuals. 
Threejs has fog built-in, see e.g.: 

https://threejs.org/docs/#api/scenes/Fog (linear density growth)
https://threejs.org/docs/#api/scenes/FogExp2 (exponential density growth)
https://threejs.org/examples/webgl_geometry_terrain_fog.html

Adding it manually is as simple as e.g.:
    app.scene.fog = new THREE.FogExp2("white", 0.025);
or
    app.scene.fog = new THREE.Fog("white", 10, 50);

but in the GUI we would need options to set color and most importantly the distance/falloff parameters in a smart way. This might also require something to allow exclusion from "fogging" certain objects like labels and thus specifying the order of objects. This would complicate things...

It would be fantastic if fog could be added to qgis2threejs.

### Example screenshots
![fog](https://user-images.githubusercontent.com/7661092/29767152-b444de36-8be1-11e7-9c4e-c2f2576dfe66.jpg)
![fogexp2](https://user-images.githubusercontent.com/7661092/29767153-b46256dc-8be1-11e7-9db4-ff49c8267585.jpg)
![nofog](https://user-images.githubusercontent.com/7661092/29767154-b4627dba-8be1-11e7-89ba-d8c1aedba44d.jpg)

**Comment by HLHJ** [comment]
I'm going to second this feature request and extend it into a more complex one. 

Fog would attenuate visibility linearly if it was perfectly black. But as it scatters light, the visibility decays exponentially with distance. Exponential fog looks much more realistic and gives a better impression of distance.

The ability to add solid and transparent volumes as well as transparent surfaces would be generally useful; geology, oceanography, and meteorology deal in volumes. The volumes could be defined by an upper and lower surface, or by several such pairs of surfaces. But as QGIS doesn't really deal with volumes, so this might be out of scope.

**Comment by kannes** [comment]
OMG, thank you @minorua!
