### ISSUE TITLE
[Enhancement Request] North Arrow/Compass

### ISSUE THREAD

**Issue by DigDigDig** [minorua/Qgis2threejs#106]
![compasstest](https://user-images.githubusercontent.com/17930616/29894657-1891370e-8da4-11e7-88db-12e2ac5ccdeb.gif)

I've implemented a north arrow in my local Qgis2threejs library and have found it very useful in presenting my visuals.

By adding a short buildCompass function I can place a secondary rendering window overtop of my main display and then call a camera to point at a windrose model while copying the location of the main camera.  

```
// Global Variables for Compass Inset
var container2,
    camera2,
    scene2,
    renderer2,
    axes2,
    secondaryCanvasWidth = 200,
    secondaryCanvasHeight = 200,
    secondaryCameraDistance = 400;

app.buildCompass = function () {
        // dom
        app.container2 = document.getElementById('inset');

        // renderer
        app.renderer2 = new THREE.WebGLRenderer({
            alpha: true,
            antialias: true
        });
        app.renderer2.setClearColor(0x000000, 0);
        app.renderer2.setSize(secondaryCanvasWidth, secondaryCanvasHeight);
        app.container2.appendChild(app.renderer2.domElement);
        // scene
        app.scene2 = new THREE.Scene();

        // camera
        app.camera2 = new THREE.PerspectiveCamera(50, secondaryCanvasWidth/ secondaryCanvasHeight, 1, 1000);

        app.camera2.up = app.camera.up; // important!
        app.scene2.add(new THREE.AmbientLight(0x999999));
};
```

Then I just copy the position of my main camera to my secondary camera, while keeping it pointed at the center of my windrose:

```
app.animate = function () {
        if (app.running) requestAnimationFrame(app.animate);
        if (app.controls) app.controls.update();
        app.camera2.position.copy(app.camera.position);
        app.camera2.position.sub(app.controls.center);
        app.camera2.position.setLength(secondaryCameraDistance);
        app.camera2.lookAt(app.scene2.position);
        app.render();
};
```

The result is a compass that always points north.  I think that this concept would be a great thing to add in the V2.0 of the plugin if it were refined a little.

**Comment by Lisek87** [comment]
Hi, This is very useful feature.  Can you explain  step by step how to use this code? i have problem with implementation.

**Comment by minorua** [comment]
@Lisek87 Yes, this is a great feature. I will implement this feature in plugin version 2.0. Please wait for a while : ).

**Comment by minorua** [comment]
@DigDigDig Thank you for your suggestion and your code contribution!
