### ISSUE TITLE
wireframe mode not trasparency

### ISSUE THREAD

**Issue by vancori** [minorua/Qgis2threejs#108]
Hi,
I need to see the DTM in 3D mode, using the plug Qgis2threejs. I can see it in wire frame mode but I need to see it in “hidden line” mode, so avoiding the transparency of wireframe. How can I do?

**Comment by DigDigDig** [comment]
Do you have an example of what you want to accomplish?  

The Three.JS EdgesGeometry helper might be useful in this situation, but I'm not quite sure exactly what you're going for...

https://threejs.org/docs/#api/geometries/EdgesGeometry

**Comment by vancori** [comment]
I am currently working on a project with QGIS for an intervisibility analysis of a wind turbine plant. Among the various documents, I have to do is to show the 3D simulation from the various photographic points of view, how you should see this wind turbine (in Collada 3D file). Instead of using the DEM model, the view is required in Wireframe mode, but not in transparent form, from which to see through! but in full color, so as to simulate the shape of the ground.
I have read the Qgis2threejs guide and I can not find the solution. In the settings for the DEM part, there is, in, the display type, the "Enable shading" item, 
![sett](https://user-images.githubusercontent.com/22771399/30391270-0ccd568a-98b9-11e7-85ef-a31053592e1b.png)
should be that, but it does not render the wireframe grid unclear
It should come this way:
![dem1](https://user-images.githubusercontent.com/22771399/30391318-358be06e-98b9-11e7-9a25-85bfee034bbd.png)

**Comment by DigDigDig** [comment]
Someone else might have a more elegant solution, but here is a quick and dirty method for you:

1. Copy your base DEM layer and hit export to Qgis2threejs.
2. Under the DEM tab select 'Display Type: Solid Color', and set that to white.
3. Under the additional DEM tab select  'Display Type: Solid Color', and set that to black.
4. Export your model.
5. Use your console or write a short javascript file that contains the following commands, substituting 'DEM_copy' for whatever the layer name of you additional DEM layer is.

```
app.scene.autoUpdate = true;
project.getLayerByName("DEM_copy").queryableObjects[0].position.z = .5;
project.getLayerByName("DEM_copy").queryableObjects[0].material.wireframe = true;
```

I turned the opacity of my black wireframe layer (DEM_copy) down a little bit.

Three.js cuts all polygons into triangles so you won't be able to get a square grid like your example image.  Maybe this will do the trick for you though!

![example-test](https://user-images.githubusercontent.com/17930616/30393802-3544481e-988f-11e7-8828-fa4959f1ece7.png)

**Comment by vancori** [comment]
Yes. The problem is this, that you've identified.
You have been very kind, to give me your solution now, which I see should work.
I tried it last night, but I have difficulty with the Python part, because I'm not a programmer.
Using QGIS with Ubuntu, how else can it be resolved?

**Comment by DigDigDig** [comment]
There isn't any Python in this solution.   What are the names of your DEM layers? If I have them then can write up an html and js file and drop them here for you to copy into your export folder.

**Comment by vancori** [comment]
Ok ... I have set the settings as you said, and save the project in FileExport.html mode?
Within an directory in mode Output HTML file path folder?
Here is the folder created on the desktop
![folder](https://user-images.githubusercontent.com/22771399/30435446-0f02c410-996a-11e7-9ebe-9fe28969467a.png)


The name of the first DEM is "DTM_dbtopo_5m"
The second DEM is "DTM_dbtopo2_5m"

**Comment by DigDigDig** [comment]
Go ahead and replace the modello_eolico.html file with the one I've posted here:

https://gist.github.com/DigDigDig/ec7e6c38b213ddb22ebc60cb98a405ba

That should do the trick for you.

-DigDigDig

**Comment by vancori** [comment]
No, it does not work. There are two other DEM files too, one is the turbine in COLLADA model, and the other are the viewpoint.
![viewdem](https://user-images.githubusercontent.com/22771399/30437707-91abdd52-996f-11e7-82e5-72f25eb021f1.png)

**Comment by vancori** [comment]
waiting moment.. I try to do another attempt.
I enter the code directly into html files created in the tmp folder

**Comment by DigDigDig** [comment]
I think that you may be exporting the file wrong.  Can you check for error messages in your web browser when you have the HTML file open?  That's the first step in debugging this.  

It might be a good idea to send a screenshot of your dat-gui panel as well, that way we can see what layers you are working with.

![example-test2](https://user-images.githubusercontent.com/17930616/30438571-86bf5020-993f-11e7-895c-1de5f826b9c0.png)

**Comment by vancori** [comment]
OK right now! I'm very happy.
![layer_ok](https://user-images.githubusercontent.com/22771399/30440407-b6bcc082-9976-11e7-85f9-7424db31c42d.png)

I made the change the html file on the ubuntu tmp directory, and then saved the files externally.
I think you should implement the direct editing in the plugin, which could be useful in many situations
You've been very kind.
Thanks a lot

**Comment by DigDigDig** [comment]
Nice!  Glad you got it working!

**Comment by lisamcravey** [comment]
Hiya, I'm trying to do the exact same thing! And not sure how to go about the step below. Can anyone give me a quick how to on this please?! 

> Use your console or write a short javascript file that contains the following commands, substituting 'DEM_copy' for whatever the layer name of you additional DEM layer is.
> app.scene.autoUpdate = true;
> project.getLayerByName("DEM_copy").queryableObjects[0].position.z = .01;
> project.getLayerByName("DEM_copy").queryableObjects[0].material.wireframe = true;

**Comment by minorua** [comment]
`Add quad wireframe` option was added in version 2.6. Solid color material + the wireframe option can do this job. Thanks.
