### ISSUE TITLE
Date and Time Display in Popup Window

### ISSUE THREAD

**Issue by DigDigDig** [minorua/Qgis2threejs#109]
I noticed that the plugin passes date/time information through the python exporter as a datetime object and never converts it back to a string before pushing out to the final javascript file.  

The result is that all date/time data reads something like "**PyQtCore.QDate(2017, 9, 13)**" instead of "**09/13/2017**".  

It looks like [using strftime would be an easy way to format the datetime ](https://stackoverflow.com/questions/10624937/convert-datetime-object-to-a-string-of-date-only-in-python)on the python side.  

I'm not much of a python developer and have little familiarity with the python side of this plugin.  Could someone suggest a change to the exporter code that would result in a clean conversion of this datetime object to a string so that it is formatted correctly on export?
![pydatetime](https://user-images.githubusercontent.com/17930616/30400830-32928eac-98a6-11e7-8f3c-5bddbc5abbd8.png)

**Comment by minorua** [comment]
already fixed
