### ISSUE TITLE
Model isn't showing

### ISSUE THREAD

**Issue by andrek42** [minorua/Qgis2threejs#112]
Sorry in advance for my lack of experience.

I've made a 3D model using the plugin in QGis with public Aster GDEM data and Sentinel 2 imagery. The result was perfect and I uploaded it to the Geopark Corumbataí website (hosted at hostinger + wordpress.org): http://geoparkcorumbatai.com.br/mapa-3d-do-geopark-corumbatai/

After working perfectly for a couple of hours, and without me changing anything (as far as I know =p), the 3D model stopped showing, while the blue canvas was still there.
So, after getting desperate, I came up here and started typing this thread, did some other tests and, suddenly, it started showing normally again.

My question is: is this a bug? Have I done something wrong? Will it keep coming and going like this?

Thanks all for the attention =)

**Comment by minorua** [comment]
It takes some time to load the page, but the model is displayed in my web browser. It may fail to be loaded if the server response is too slow.

**Comment by andrek42** [comment]
Yeah it might be that since the .js file is almost 60 MB large. I am confused because sometimes it loads in few minutes and other times only after reloading the page many times. Thanks for the reply!

**Comment by itarec1988** [comment]
Hi! This might be related to the question posted by andrek42. I am trying to visualize a DEM (SRTM 1 arc second) with the Qgis2threejs plugin but it is not showing on the browser (Googlechrome version 63.0.3239.132). I already waited for quite some time and its stuck. The controls are displayed but there is no 3D image of the DEM I am trying to look at..

Could I get some hint here?

Thank you

**Comment by DigDigDig** [comment]
itarec1988, can you give us a little more information to work off of here?  Try these steps to debug and let us know what you find out.

1. Check the developers console for any error messages.
2. Enter `console.log(project.layers[0])` and then paste the return here.

Hopefully we can help you out once we track down the underlying issue.

**Comment by itarec1988** [comment]
DigDigDig I tried in other computer and it worked, so I think it s related to the version of google chrome. Nevertheless, I will check the console and posted here for further information.

Thank you!

**Comment by itarec1988** [comment]
DigDigDig--This is what the message log gives me as warning. Is it useful? 
I could not run the command you recommended. I tried it in the python console but it did not work.. I hope this helps tracking the issue.. Thanks..

2018-02-05T22:17:53	1	warning:/Users/santiago/.qgis2/python/plugins/Qgis2threejs/datamanager.py:84: DeprecationWarning: QgsMapCanvas.map() is deprecated
			  return tools.base64image(canvas.map().contentImage())
			
			traceback:  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/GdalTools/GdalTools.py", line 374, in doProjection
			    self.runToolDialog(d)
			  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/GdalTools/GdalTools.py", line 413, in runToolDialog
			    dlg.exec_()
			  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/GdalTools/tools/widgetPluginBase.py", line 66, in exec_
			    return self.base.exec_()
			  File "/Users/santiago/.qgis2/python/plugins/Qgis2threejs/qgis2threejs.py", line 109, in run
			    ret = dialog.exec_()
			  File "/Users/santiago/.qgis2/python/plugins/Qgis2threejs/qgis2threejsdialog.py", line 544, in run
			    ret = exportToThreeJS(export_settings, self.iface.legendInterface(), self.objectTypeManager, self.progress)
			  File "/Users/santiago/.qgis2/python/plugins/Qgis2threejs/export.py", line 275, in exportToThreeJS
			    writer.writeImages()
			  File "/Users/santiago/.qgis2/python/plugins/Qgis2threejs/export.py", line 152, in writeImages
			    self.imageManager.write(self)
			  File "/Users/santiago/.qgis2/python/plugins/Qgis2threejs/datamanager.py", line 250, in write
			    args = (index, size.width(), size.height(), self.mapCanvasImage(transp_background))
