### ISSUE TITLE
Error in vertical exaggeration

### ISSUE THREAD

**Issue by ronbm08** [minorua/Qgis2threejs#114]
![image](https://user-images.githubusercontent.com/1429709/33281125-c841caf0-d369-11e7-9431-57042bce7051.png)

Hello, I am new using this plugin and I am having this problem in the image, when placing a value less than 1.5 in vertical exaggeration everything diminishes even the 3d model I do not know what I am doing wrong ... you could help me

**Comment by DigDigDig** [comment]
Hi @ronbm08.  

I would check two things:

1. Is there an error in the DEM that you are using?  
2. Is your project CRS set correctly?  I've noticed that the vertical exaggeration can be under or over exaggerated if they projection is not correct for the data I am using.

**Comment by ronbm08** [comment]
Hi @DigDigDig 
thanks that helps a lot in addition to adjust the vertical shift and now it's much better
