### ISSUE TITLE
ASC file with on the fly projection

### ISSUE THREAD

**Issue by I-Rod-I** [minorua/Qgis2threejs#120]
Hello, 

I have a dtm file (.asc). qgis2threejs shows correctly the elevation only if I configure Qgis with the crs of the dtm.

I would like to display the 3d geometry in a different crs from the dtm file with "on the fly projection".
If I don't use the crs of the dtm, it shows always a flat plane without any elevation and the collada files exported are corrupted.
There isn't the message in  qgis2threejs: "the unit of current CRS is degrees, so terrain may not appear well."

Does qgis2threejs allow an export in a different crs from the dtm data?

**Comment by minorua** [comment]
Yes. Set CRS of the DTM layer and CRS of the project and enable on-the-fly projection, then the plugin can reproject and export the DTM correctly.

**Comment by I-Rod-I** [comment]
The CRS of the DTM layer is 2154. I enabled on-the-fly projection.
That works well when I set the CRS of the project to 2154.

When I set the CRS of the project to 32630, it shows no elevation. Only a flat plane.
The log console of Qgis2three.js indicates in this case the following message :
_2018-02-05T17:35:01	1	[propertypages.py] Cannot restore layerImageIds property_

Thank you for the reply!

**Comment by I-Rod-I** [comment]
I'm a bit confused.
Is that a bug or does it come from the data?

**Comment by I-Rod-I** [comment]
I projected the DTM layer myself in 32630 and used it as input for QGis2Three.js to have the correct elevation in the crs desired.
