### ISSUE TITLE
Using 3D shapefiles in Qgis2threejs

### ISSUE THREAD

**Issue by jsine** [minorua/Qgis2threejs#129]
I'm using QGIS version 3.01. I've been modeling buildings and used QGIS own 3Dview. 
I noticed that Qgis2threejs plugin is now available in version 3.0.  It seems that Qgis2threejs plugin does not understand 3D polygons? Is there a way to use 3D polygons in this plugin? It would be great to get LOD2 buildings to web browser but it there ain't no other way to do this than Qgis2threejs plugin?

![image](https://user-images.githubusercontent.com/39048992/39696487-86196d98-51f6-11e8-8353-15a1a16ec14d.png)
Image from Qgis 3d view.

![image](https://user-images.githubusercontent.com/39048992/39697252-f41a3974-51f8-11e8-851f-b4f9a6b6dbd4.png)

Image from Qgis2threejs plugin.

Roof and walls are in separate layers.

Wall layer propeties:
![image](https://user-images.githubusercontent.com/39048992/39697350-5179d624-51f9-11e8-9ccc-836999538fab.png)

Roof layer properties:

![image](https://user-images.githubusercontent.com/39048992/39697387-7462d802-51f9-11e8-9697-ffb069bb0f93.png)

**Comment by minorua** [comment]
Triangular Mesh type has been added in version 2.2. Qgis2threejs doesn't have ability to triangulate 3D polygons, so you need to triangulate 3D polygons using tessellation algorism of Processing first.
