### ISSUE TITLE
QGIS master (3.1) crashes when closing the plugin windows

### ISSUE THREAD

**Issue by ghtmtt** [minorua/Qgis2threejs#131]
Tested with many different layers (in many different CRS) but the plugin always makes QGIS crash when closing the window. The only clue I have in the terminal is:

```
QGIS died on signal 11Aborted
```

tested on QGIS 3.1 compiled on a Debian Sid computer

**Comment by nirvn** [comment]
I see this crash too.

**Comment by minorua** [comment]
Duplicate of #128
