### ISSUE TITLE
Plugin crashes QGIS on api call

### ISSUE THREAD

**Issue by bstroebl** [minorua/Qgis2threejs#134]
steps to reproduce
in Python console enter
```
t=QgsMapToolAdvancedDigitizing(iface.mapCanvas(),iface.cadDockWidget())
t.createRubberBand()
```
Crash happens definitely on Win7 QGIS 3.0.3 (osgeo install) see [this issue](https://github.com/bstroebl/DigitizingTools/issues/30) and most probably also on [Win10](https://github.com/bstroebl/DigitizingTools/issues/29) and [MacOS](https://github.com/bstroebl/DigitizingTools/issues/28)
I cannot reproduce it on Ubuntu16.04 (probably because it has an older Qt (Version 5.5))

**Comment by minorua** [comment]
This is not an issue of Qgis2threejs plugin.

**Comment by bstroebl** [comment]
Hmm, if you have Qgis2threejs loaded QGIS crashes when entering the code I gave above, if you unload it QGIS does not crash. I would therefore think it is caused by the plugin.

**Comment by minorua** [comment]
I can reproduce the crash without Qgis2threejs plugin installed. 

In python console of QGIS 3.2 on Win10:
```
from PyQt5 import Qt
t=QgsMapToolAdvancedDigitizing(iface.mapCanvas(),iface.cadDockWidget())
t.createRubberBand()
```

So I think I can close this issue.

**Comment by bstroebl** [comment]
Interesting, I tested with QGIS - uhhm - 3.0.? on Win7 when I raised the issue and deactivating the plugin avoided the crash.
Seems to be a ticket for QGIS itself then. I will test as soon as I have an appropriate system installed.

**Comment by minorua** [comment]
"from PyQt5.Qt import Qt" is bad. The Qt module should be import from PyQt5.QtCore.

**Comment by bstroebl** [comment]
AFAIK you should do
`from qgis.PyQt import QtCore`
at least that is what [qgis2to3 ](https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3)script tells you
