### ISSUE TITLE
Objects removed from version 2.0

### ISSUE THREAD

**Issue by Denikine** [minorua/Qgis2threejs#136]
Hello everyone,

I saw that 3 objects have been removed from the version 2.0 of the plugin : Collada, JSON and Icon.
Since I am using the Icon feature in many of my projects, I would like to know if there is any way that it will come back.
Should I come back to QGis 2.x or wait for a new version of the plugin with Icons ?

(By the way, I have the same problem as some other users : when I close the plugin, QGis crashes. But I won't create a new issue for this if it has already been reported ;D )

Thanks for your help and advice !

**Comment by Denikine** [comment]
Hello again,

I finally decided to downgrade to QGis 2.18 and qgis2threejs 1.4.2.
I am still hoping for the coming back of the icons, which could enable me to  get QGis 3.0 and the latest version of the plugin.

Thanks for this useful plugin and the hard work !

**Comment by jukos** [comment]
Hello,
I missed also the object type "collada model" for QGIS 3 / Qgis2threejs 2.0.1.
When could I work with this object type? Any time-plans?

Thank you and greetings
Jürgen
