### ISSUE TITLE
project is not defined

### ISSUE THREAD

**Issue by davidNDU** [minorua/Qgis2threejs#137]
running with QGIS 2.18.15 and Qgis2threejs 1.4.2
Exporting to FireFox 61.0 [1], Chrome 67.0.3396.99 [2], Edge 42.17134.1.0 [3], Safari 5.1.7 [4]
using a DEM, EPSG:32636, WGS 84 / UTM zone 36N
https://get.webgl.org/ shows the spinning cube on all browsers apart from Safari.

The browser does not show the model, only the blue sky background.
I tried to change the output folder to that one of the *.qgs, and renamed the *.qgs to project.qgs with no effect. 

The error messages from the console are as following:
[1]
> ReferenceError: project is not defined Qgis2threejs.html:57:1
> <anonym>
> file:///C:/Users/david/Desktop/GIS/Watershed/Qgis2threejs.html:57:1

[2]
> Qgis2threejs.html:57 Uncaught ReferenceError: project is not defined
>     at Qgis2threejs.html:57

[3]
> SCRIPT5009: 'project' is not defined
> Qgis2threejs.html (56,1)

**Comment by DigDigDig** [comment]
It looks like you are missing the .js file associated with the project export. The actual project data that gets pushed out from the plugin is a .js file with the same name as your project .html file.  So, if you named your project "watershed.html" in the exporter then you would also get a "watershed.js" file accompanying it. 

The Qgis2threejs JavaScript library that loads your project data is called "Qgis2threejs.js".  My guess is that naming your project "Qgis2threejs.html" in the exporter caused the project data to be overwritten or something.

Try exporting your project with a different name and see if you still get the error.

![image](https://user-images.githubusercontent.com/17930616/42043565-c0524c18-7ac4-11e8-8d2f-392b40e95ee4.png)

**Comment by davidNDU** [comment]
Thank you, DigDigDig!
That was the case, renaming did the job.
