### ISSUE TITLE
Fade in/out layer on visibility change?

### ISSUE THREAD

**Issue by brianh94** [minorua/Qgis2threejs#138]
Hi,

Have been wondering if it is possible to add animations (fade) to layers? I wanted to try something with jQuery fade methods but the more I think about it, the more it sounds like it won't work.
Anyone have any tips on this?

Thanks!

**Comment by DigDigDig** [comment]
You'll probably be able to rig something up with tween.js.  I've used this to move the camera around preset views in my scenes.

https://github.com/tweenjs/tween.js/

**Comment by minorua** [comment]
Opacity transition animation is available in version 2.7. Thanks!
