### ISSUE TITLE
[Feature Request] Default Visibility on Load

### ISSUE THREAD

**Issue by Kapanther** [minorua/Qgis2threejs#140]
Allow the default visibility of a layer to be set in the gui. So that it is not loaded on startup of viewer.

see [https://ibb.co/nhHTDd](url)
![image](https://user-images.githubusercontent.com/12637127/42741822-f2dd8ad4-88f8-11e8-9106-a6321b6389c3.png)

**Comment by brianh94** [comment]
This would be a nice addition to the GUI. 
I've added a few lines of code to my projects that accomplish the same thing.
More details here: https://github.com/minorua/Qgis2threejs/issues/101

**Comment by minorua** [comment]
implemented
