### ISSUE TITLE
[Feature Request] Preview Timeout for larger complex models

### ISSUE THREAD

**Issue by Kapanther** [minorua/Qgis2threejs#142]
On some more complex models the application tends to freeze on changes to the viewer. Some changes will be quite simple and the preview rebuilds fine. But some changes could be quite complex and the preview will either hang forever or crash. This could be prevented by adding a preview timeout? And notifying user if timeout is reached.

![image](https://user-images.githubusercontent.com/12637127/42742012-9f7f83c2-88fa-11e8-9f07-4159394c6431.png)
.

**Comment by minorua** [comment]
In master, the exporter became more responsive. Layer data are built in a worker thread and passed to the web page working in GUI thread, and then 3D objects are built in the web page.
