### ISSUE TITLE
Unable to view in Chrome - This browser doesn't allow loading local files via Ajax.

### ISSUE THREAD

**Issue by brianh94** [minorua/Qgis2threejs#144]
Hi all,

I've just updated to the newest version of QGIS and the v2.0 of qgis2threejs. I'm unable to open my export with this message:
![image](https://user-images.githubusercontent.com/29439240/42788353-e4170410-8913-11e8-90b3-a688a85240ae.png)

I've been using v1.4.2 of this plugin and never seen this error before in any browser. I'm able to open the page in Firefox, but not in Chrome. 
I've looked through the export settings and can't find anything regarding this error.

Thanks!

**Comment by brianh94** [comment]
I think I found the source of this error. It looks like v2.0 of Qgis2threejs saves layer and DEM info in the data folder instead of having it encoded in base64 in JS like in previous versions.

@minorua Is there a way to change the encoding type or should I use the older version? Thanks!

**Comment by minorua** [comment]
Fixed the hyperlink to wiki page.

@brianh94 From the wiki page:
> Some web browsers don't allow loading local files via Ajax. If you want to check your exported pages in local file system, use a web browser that allows loading local files via Ajax (e.g. FireFox, Microsoft Edge).

**Comment by minorua** [comment]
Please use a web browser that allows loading local files via Ajax or upload your exports to a web server.
