### ISSUE TITLE
CSS .print-label is not transfering properties to the function renderLabels

### ISSUE THREAD

**Issue by FloRiderIntheSky** [minorua/Qgis2threejs#146]
Hallo, 
i tried to change the .print-label properties in the CSS file. There was no succues in FF or Chrome.
For example i added:

	font-family: "Verdana", Geneva, sans-serif;
	  font-size: smaller;
	  font-weight: 900;

There was no result in the label rendering.

But the Class Selector .label  does have a effect on the rendering of labels. 
I couldt find the issus in the .js file. Maybe there is none and i was not able to get it right.

Can you confirm this issue?

Kind regardas

**Comment by minorua** [comment]
`.print-label` class is used when saving a scene as an image file. Only `color` and `font` properties are read in the renderLabels function.

**Comment by FloRiderIntheSky** [comment]
I see, thank you very much for the answer.
