### ISSUE TITLE
Wireframe shows unwanted diagonals

### ISSUE THREAD

**Issue by RSchwarz98** [minorua/Qgis2threejs#152]
I am wanting to view a wireframe of a set of buildings, however instead of just showing the edges it also shows some diagonals (in the color of the faces).

![2](https://user-images.githubusercontent.com/43738416/46270925-5dd37580-c58d-11e8-8576-4c4447824cdd.PNG)

How can I make it so that I just have the edges?

**Comment by wickerman123** [comment]
The mesh has to be triangulated for it to be viewed in 3D, that's what you're seeing.
