### ISSUE TITLE
creates "just" a tunnel

### ISSUE THREAD

**Issue by rlange77** [minorua/Qgis2threejs#157]
Hi,
I'm very new with Qgis. I try to create a map of a lake. 
I use reefmaster to render the files from the sonar.
Reefmaster exports an asc file which I import as raster into QGIS.
If I use Qgis2threejs with this layer I get the map of my like but the profile is missing.
It creates a tunnel.
See here: 
http://www.opentrabi.de/see/index.html

The source asc file is this:
https://www.dropbox.com/s/49a6cbv5a1nf5bo/Zwenkauer-See-Test.asc?dl=0

Can you help me with it?
What do I do wrong?

Thanks Rob

**Comment by minorua** [comment]
Oops. The plugin doesn't seem to read elevation values from the asc file. I needed to convert it to a GeoTIFF file.

**Comment by minorua** [comment]
Or a projection file needs to be in the same directory as asc file.

Zwenkauer-See-Test.prj
```
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]
```

**Comment by rlange77** [comment]
how did you convert into GeoTIFF?
CRS is EPSG:4326
here the prj file.
https://www.dropbox.com/s/gm9bz5ch59b8soj/Zwenkauer-See-Test.prj?dl=0

thanks for helping mate!!!

**Comment by minorua** [comment]
> how did you convert into GeoTIFF?

`Layer's context menu > Export > Save As` or `Menu bar > Raster > Conversion > Translate (Convert Format)`.

**Comment by rlange77** [comment]
Hi Buddy,
Can I contact you directly? Need some help and happy to pay for the service!
I can’t get it working!

Viele Grüße

Robert Lange
PADI Course Director und Trimix Instructor Trainer
TAUCHBASIS ZWENKAUER SEE
https://tauchbasis-zwenkauer-see.de
info@tauchbasis-zwenkauer-see.de
+49 151 161 666 66

**Comment by minorua** [comment]
> Can I contact you directly?

Of cource. :-)

> I can’t get it working!

Have you read this tutorial?
https://qgis2threejs.readthedocs.io/en/docs/Tutorial.html

CRS of the data source is same. The procedure will be very similar to this.

BTW, my e-mail address is akaginch@gmail.com. Reply to an e-mail from GitHub will appear as a comment on GitHub Issue.

**Comment by rlange77** [comment]
Hi Buddy,
Thanks for helping.

I have tried it again and still get the same tunnel result.
If you can have a look at the steps I did and what I do wrong I would be happy :)
Thanks a lot!

Rob

 

 

 

Von: Minoru Akagi [mailto:notifications@github.com] 
Gesendet: Freitag, 30. November 2018 02:00
An: minorua/Qgis2threejs <Qgis2threejs@noreply.github.com>
Cc: rlange77 <rlange77@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [minorua/Qgis2threejs] creates "just" a tunnel (#157)

 

Can I contact you directly?

Of cource. :-)

I can’t get it working!

Have you read this tutorial?
https://qgis2threejs.readthedocs.io/en/docs/Tutorial.html

CRS of the data source is same. The procedure will be very similar to this.

BTW, my e-mail address is akaginch@gmail.com <mailto:akaginch@gmail.com> . Reply to an e-mail from GitHub will appear as a comment on GitHub Issue.
