### ISSUE TITLE
relation coordinates jsfile with real coordinates

### ISSUE THREAD

**Issue by paulopires16** [minorua/Qgis2threejs#158]
What are the relation from coordinates in jsfile with real coordinates?
Thanks

**Comment by larsgrobe** [comment]
I have also been wondering. As far as I understand, the canvas in QGis defines the model extent, and its dimensions are set by the `basewidth` variable (default being 100) in the scene settings.

So to my understanding, one has to write down the canvas extents (in physical units, e.g. meters) before exporting, and then scale the exported model by _w_/100 with _w_ being the larger dimension of the canvas to get a 3D model in proper scale.

Is this correct? Would it be possible to add an option that just keeps the coordinates as they are? I believe the the extension is used as much to export to other modelling tools (where scale has to be maintained) as for visualisation (where downscaling makes sense).

**Comment by minorua** [comment]
The width of map extent to export can now be set in scene settings dialog. The corresponding size in the 3D world is the `base width` of the world coordinates group. If you set the same value for both settings, you can export 3D model in map units.
