### ISSUE TITLE
Cannot activate plugin version 2.3 on windows 8.1 

### ISSUE THREAD

**Issue by alonsoac** [minorua/Qgis2threejs#162]
When I activate the plugin in the plugins list I get an error about Windows not supporting a Bluetooh API, then QGIS crashes.
QGIS 3.4.4 64 bit , installed via OSGeo4W64
Windows 8.1 64bit
Plugin version 1.4.2 works ok in QIGS 2.18

**Comment by Guimelar** [comment]
I have same problem. Occurs in all windows 8.1, I think

**Comment by minorua** [comment]
See this comment: http://python.6.x6.nabble.com/This-Windows-version-does-not-support-the-required-Bluetooth-API-tp5237318p5237320.html

I'm going to fix this issue by replacing `from PyQt5.Qt import Qt` with `from PyQt5.QtCore import Qt`.

**Comment by Guimelar** [comment]
Hello, the fix in v2.3.1 don't work on qgis 3.4 and windows 8.1
