### ISSUE TITLE
Command / Custom Plane options & north arrow not shown on touchscreen devices

### ISSUE THREAD

**Issue by Yakwrangler** [minorua/Qgis2threejs#170]
Created 3D model in QGIS 3.4.5 & Qgis2threejs 2.3.1 ... displays as expected from web site for PCs / laptops using the '3D Viewer with dat-gui panel' template.

But on touchscreen devices the north arrow is not displayed and the Menu - > Command  & Custom Plane tabs are empty.

As tested on a variety of Android / Apple phones & tablets, as per the URL shown on the screenshot.

Is this an issue with the dat-gui_panel.js script perhaps or just a configuration issue?

![image](https://user-images.githubusercontent.com/49032554/55164698-0a209e00-5164-11e9-8751-fe2529bc07b6.png)

**Comment by minorua** [comment]
Thanks!
