### ISSUE TITLE
QtWebKit

### ISSUE THREAD

**Issue by taylankarakurt** [minorua/Qgis2threejs#176]
Hi everyone. PyQt5 does not have QtWebKit anymore. Instead of it QtWebEngine took the place. Change code according to this ? Because I can't install plugin on QGis. 

Cheers.

**Comment by kannes** [comment]
I think this is not relevant anymore, qgis2threejs works perfectly well on modern QGIS :)

**Comment by minorua** [comment]
Qgis2threejs exporter can now work with Qt web engine view (not perfect, and needs some changes on QGIS code). See also https://github.com/minorua/Qgis2threejs/issues/248.
