### ISSUE TITLE
Not running locally, only for 3D made with newer Q2t (but older versions work fine)

### ISSUE THREAD

**Issue by smaprs** [minorua/Qgis2threejs#184]
Hi, first of all thank you much for your amazing work. 
The issue is that when loading local files index.html (double-clicking) in Google Chrome 76.0.3809.132 64 bits:
A) For new 3D models made in QGIS-3.4.11 (installed yesterday and working), with Qgis2threejs version 2.3.1, it does not work: 
a popup-bar shows this error message: "This browser doesn't allow loading local files via Ajax. See plugin wiki page for details." Both for dat-gui and non-gui.
B) But for older 3D models it keeps working:
QGIS-2.18.27 with older Qgis2threejs plugin [2014 var Q3D = {VERSION: "1.4.2"}].
Also, when running https://get.webgl.org/, the browser works normally. All WebGL flags in chrome are enabled as always were. Any other webgl sites working. 
What possible solution? Thanks. smaprs

**Comment by smaprs** [comment]
More info: also in Firefox 69.0 (64-bits) the 3D made by Qgis2threejs 2.3.1 doesn't work (but by the older Qgis2threejs works), I've tested now (WINDOWS 10 64bits in AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G 3.10GHz / 16GB RAM).

**Comment by minorua** [comment]
Plugin version 2.4 has `Enable the viewer to run locally` option in the export to web dialog.
