### ISSUE TITLE
Setting the Initial Camera Position in exported files

### ISSUE THREAD

**Issue by LovroLKP** [minorua/Qgis2threejs#185]
Dear author and contributors,

first I wanted to say a big THANK YOU for all the energy and work you have put into this plugin. ITS GREAT!!! I read the Documentation files which are very useful, as are the threads here.
Ive been using it for rendering surfaces from LiDAR data and it works great.
Since I am a non-experienced web (or any other kind of a) programmer, so I have been having an issue in a final step, "beauty fixes". 

I wanted to change the target of the initial camera view. 
CASE: [mywebmodel](https://zlk.si/3D/adpirum/)
As by default, the initial camera view target is in the center of the model, at its base. I wanted to raise this targets Z to the model surface.

I went through the code of the exported files and tried to find the parameters defining this, but through trial and error, could not find the right part of the code. I would be very grateful if someone could point me into the right direction.

Sorry for wasting your time with such a noob question, especially if this was answered before.

Thanks again for such a great product!

**Comment by minorua** [comment]
Plugin version 2.4 has `Preserve the current viewpoint` option in the export to web dialog. The option and some options in the scene settings dialog may be useful for the fixes.
