### ISSUE TITLE
[QUESTION] Popup window size parameters

### ISSUE THREAD

**Issue by JakubPelka** [minorua/Qgis2threejs#186]
Hello, 
I did search in index.html as well as in control settings, but didn't succeed.
Is there any option to adjust popup attribute window size? any place that width value could be set?
I am using photo as an attribute and I'd like to avoid need of scrolling to sides (in kiosk mode with touchscreen it is very unfriendly).
Will be really glad for your help.
Jakub

**Comment by minorua** [comment]
Qgis2threejs.css is the place.
https://github.com/minorua/Qgis2threejs/blob/master/css/Qgis2threejs.css#L88

**Comment by JakubPelka** [comment]
Thanks! It was what I was looking for! :)
