### ISSUE TITLE
This browser doesn't allow loading local files via Ajax. See plugin wiki page for details

### ISSUE THREAD

**Issue by cesarcorreo** [minorua/Qgis2threejs#188]
I know that the issue was closed but I don't find the way to open the model created with QGIS 3.8.3 and plugin version 2.4. I tried to open the model with Chrome, firefox and explorer.
Thanks

**Comment by jonnyforestGIS** [comment]
Hi, @cesarcorreo can you share the project to test?

**Comment by cesarcorreo** [comment]
Sure, 
[Model-Check.zip](https://github.com/minorua/Qgis2threejs/files/3777464/Model-Check.zip)
Thanks for your interest

**Comment by minorua** [comment]
@cesarcorreo Did you check the `Enable the viewer to run locally` option in the export to web dialog? If the option was checked, there should be scene.js under data/index directory instead of scene.json.

**Comment by cesarcorreo** [comment]
Really thanks,
I didn't see the option.
Now it working perfectly
*________________*


*César Herrera Lindo <http://www.cesarpagina.com>*

**Comment by furzedo** [comment]
Hi @minorua,

I am also facing this issue when loading a local model in Chrome (79.0.3945.130). I tried to export the model using the "Enable the viewer to run locally" option but I'm afraid I cannot find it in the export dialog. The attached image shows what I see in the dialog window:

![image](https://user-images.githubusercontent.com/11993908/73904246-1c707a00-48e7-11ea-9c59-b4bc9f21ae6e.png)

I'm running Qgis2threejs 2.3.1 on QGIS 3.10.0.

Please advise.

Thank you

**Comment by cesarcorreo** [comment]
You have to update to the last version of the plugin (2.4.2).
Its works perfectly

[image: image.png]

*________________*


*César Herrera Lindo <http://www.cesarpagina.com>*

**Comment by furzedo** [comment]
Hi @cesarcorreo,

Shame on me. I don't know why, but I assumed my plugin was updated. Yet, as you could notice, it wasn't.

After updating it, all problems solved.

Thanks a lot!
