### ISSUE TITLE
"custom plane" is not enabling in dat-gui panel

### ISSUE THREAD

**Issue by smaprs** [minorua/Qgis2threejs#192]
Hi, as always, congrats for this wonderful plugin. 
I report here that the "custom plane" is not opening (or enabling) in the dat-gui panel. Its label is shown, but empty. In previous version it was enabled by default. It was very usefull to test water levels. Thank you much!

**Comment by LECNA** [comment]
Hi, 

I just complete this issue. I have the same problem. The label "Custom plane" is shown but empty. 
I think a mistake appears in data-gui_panel but I don't find it.
Someone knows how to do ?

However, thanks you very much for this wonderful job.

**Comment by minorua** [comment]
This should be already fixed. Thanks!
