### ISSUE TITLE
Web Export not working

### ISSUE THREAD

**Issue by SebastianKasan** [minorua/Qgis2threejs#193]
Hi there, 
I have put a model together that works perfectly with the normal QGIS2threejs viewer. But unfortunately, the web export is not working. I proceeds without error message but the window in any explorer shows only an empty space and the legend lists only one shapelayer (which is also not displayed). 

Pressing F12 it says, TypeError: This model is undefined.

I have loaded 
1 XYZ
1 .tif
2 Shape ...layers

![grafik](https://user-images.githubusercontent.com/39992733/69642399-fcf4df80-1061-11ea-86f1-3b80da065230.png)

Any ideas what I can check?

Version is 2.4.1 (Plugin) and 3.4 Madeira for QGIS

**Comment by karl-magnus** [comment]
Hi!
We are experiencing the same thing. 

> TypeError: _this.models is undefined

I'm attaching the viewer directory and qgis project with data for testing and reproducing the error. Thanks for a great plugin!

Plugin version 2.4.1, QGIS 3.10.1, Models made in Sketchup

[3d.zip](https://github.com/minorua/Qgis2threejs/files/4063448/3d.zip)
[test3d.zip](https://github.com/minorua/Qgis2threejs/files/4063449/test3d.zip)

**Comment by minorua** [comment]
@karl-magnus Thank you for the attached files.

**Comment by karl-magnus** [comment]
@minorua Thank you for fixing it.
