### ISSUE TITLE
How to reproduce the example forest-basin?

### ISSUE THREAD

**Issue by maxhaz** [minorua/Qgis2threejs#194]
The plugin is outstanding. Congratulation.

Not an issue but one question

How to reproduce the example [forest-basin](https://qgis2threejs-examples-24.netlify.com/forest_basins.html)?
I'd like to make also some control buttons with layer selections and 3Dphoto.

**Comment by LovroLKP** [comment]
Hello,

not certain with which step in the proces are you having trouble with, there are 2 main steps in exporting 3D map from QGis using this plugin. 

First step is setting your map data in Qgis for a new project or use an exsisting project. Forest-basin map has 3 raster layers (one that is read as DEM which will be the source of 3D surface, slope layer and surface photo layer) and I think 2 vector layers (points layer and area layer for basins). When finished, zoom to the area you would like to export. 

The second step is to open Qgis2threejs plugin. Here you can set how the plugin will render your Qgis layers into JS. It has a lot of options what to do with different data or how to render it. You can choose a prefered output framework (desktop, mobile). 

This is in short. I hope this anwsers what you were lookin for... If I misunderstood your question, please tell so I can delete the post.

**Comment by maxhaz** [comment]
Thx @LovroLKP, I got it right. I overthought the usage ; the plugin keeps things very easy. 
Really great job on this. @minorua , is there any way to contact you directly?

**Comment by kannes** [comment]
I think this can be closed :)

**Comment by maxhaz** [comment]
@kannes Sure!

**Comment by jlpoolen** [comment]
Here's the answer to my question posted 4 hours ago in this topic:  The project has a directory test/data where there is a project file, test/data/testproject1.qgs , with supporting files.  I tried to export it and the resulting web page was empty.  I'll be logging an issue in this project about that result.
