### ISSUE TITLE
Infinite vertical exaggeration? Exporter problem

### ISSUE THREAD

**Issue by xlfrglrt1** [minorua/Qgis2threejs#195]
Hi I am trying to make a 3D map using the Qgis2threejs Exporter but keep getting a problem rendering the selected DEM layer. Please see the image:
![3D exporter image](https://user-images.githubusercontent.com/58314399/69835888-82f66d80-1290-11ea-9052-da5edd6ff8ad.JPG)

Any advice as to how I can identify and correct the issue would be greatly appreciated.
Regards,
Jim.

**Comment by fabiomalf** [comment]
I had this problem when the 3D is at the border of DEM. ,Generally a slight zoom in (pressing shift) solve  my problem.

**Comment by xlfrglrt1** [comment]
Hi thanks for the advice. That doesn't seem to work for me, but I decided not to use the plugin and instead use the 3D viewer which works fine for rendering the map in 3D.
Thanks.

**Comment by minorua** [comment]
The CRS should be a projected coordinate system, not be EPSG:4326.

**Comment by xlfrglrt1** [comment]
Thanks you're exactly right. I have corrected the problem.
