### ISSUE TITLE
AR Mode with Camera instead of Backgournd

### ISSUE THREAD

**Issue by MyGIS** [minorua/Qgis2threejs#196]
Hello,
Is it possible to have the camera as a background instead of the "Sky" or solid background? (When using the AR option on the phone)
Thanks.

**Comment by minorua** [comment]
The feature exists, but is still experimental and not well-maintained.

**Comment by MyGIS** [comment]
If you need tester please let me know.

**Comment by minorua** [comment]
It worked on my mobile device before but now doesn't seem to work.

@MyGIS Thanks.

**Comment by MyGIS** [comment]
Thanks @minorua , you know where to find me if you need to test future versions.
