### ISSUE TITLE
QGIS2THREEJS export web problem

### ISSUE THREAD

**Issue by LECNA** [minorua/Qgis2threejs#199]
Hi everyone, 

( I am French so I am sorry in advance for my bad english ! )

I have a problem with Qgis2threejs plugin. I have a 3D model project to show a piece of territory in 3D. I use DEM (for the topography), Icons (for the trees) and model files in .dae (for the buildings). When I use the Qgis2threejs plugin, all this elements are shown in the preview. But when I try to export this with the "Export to web" option, my browser show an empty page... I tried to export my project without my 3D model (in .dae) and it's working. 

Do you know why the browser don't show my project with my 3D models ? And do you know how I can fix this problem ? 

Thank you for the answers. 

![Preview](https://user-images.githubusercontent.com/58300956/72516932-cc0b7c80-3852-11ea-98ff-4b05b2475b54.png)

![export2web](https://user-images.githubusercontent.com/58300956/72516904-c0b85100-3852-11ea-8b6a-af4909ea7be2.png)

**Comment by minorua** [comment]
Fixed in 4b7cd6b.

**Comment by LECNA** [comment]
Thank you very much for fixing it. 

It's working very nice on Microsoft edge but in Mozilla Firefox my 3D models are not load. The loading bar in the head of the browser is blocked. I don't know why. Even if I wait a long time my 3D models aren't load.

![edge](https://user-images.githubusercontent.com/58300956/72717560-87465500-3b74-11ea-9227-cb4856cd4a4a.png)

 ![mozilla](https://user-images.githubusercontent.com/58300956/72717547-7d245680-3b74-11ea-9654-dde11edb3e4a.png)
