### ISSUE TITLE
Plugin 2.4.2 - Various Layer Issues

### ISSUE THREAD

**Issue by Yakwrangler** [minorua/Qgis2threejs#201]
Viewer with Dat-Gui:
1 - regardless of layer property 'Visible on Load' checkbox setting the model always loads with all  layers visible
2 - as reported elsewhere the useful 'Custom Plane' function does not work either

Mobile:
3 - clicking Layer List icon does not bring up layer menu, only creates a small white rectangle at top left of screen (without function)

Thanks, Rob

**Comment by minorua** [comment]
@Yakwrangler All the bugs you mentioned above were fixed. Thanks.
