### ISSUE TITLE
Pan vertivally not horizontally [question]

### ISSUE THREAD

**Issue by Styrian123** [minorua/Qgis2threejs#213]
![overview](https://user-images.githubusercontent.com/59958694/79462564-f4dd1280-7ff7-11ea-9c89-44794223c64c.png)
![problem](https://user-images.githubusercontent.com/59958694/79462571-f7d80300-7ff7-11ea-83cd-f019b1e1fef1.png)

Hi,
I am an extensive user of your plug-in and i really appreciate your work.
I am struggling with panning respectively rotating functionality:
If I navigatie to a summit in my elevation model (the camera is at the position of the summit) I can't look upward to an other summit or even horizontally. The camera always rotates vertically down to the center of the model.
Maybe I wrongly remember but the orbit control in plug-in version 1.x allowed such camera moves, but version 2.x doesn't?
Is there a way to change, let's say some lines in 
orbitcontrols.js, to change the pan behaviour from horizontal to vertical panning?

Kind regards
C

**Comment by minorua** [comment]
The vertical panning (tilting) can be done with a keyboard, which is still available in 2.x.

![image](https://user-images.githubusercontent.com/2672095/79519339-8a2ae600-808e-11ea-944e-89924b1aec50.png)

**Comment by Styrian123** [comment]
Someone how knows how to read - especially the help pup-up - will be a winner :-)
Thank you a lot for your fast help and answer!

Kind regards,
C
