### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by Josep1965** [minorua/Qgis2threejs#214]
Im trying to load a DEM into Qgis2Threejs to see it in ·3D, but when I do it appears like that:

¨No 3D objects were rendered? There is a compatibility issue with QGIS 3D view. You need to close QGIS 3D view(s) and restart QGIS to use this preview.¨
I check everything and all is ok, my qgis version is 3.10.

May anybody help me?

**Comment by minorua** [comment]
This is a known issue (for example, #147, #221).
