### ISSUE TITLE
new project new profile compatibility issue with QGIS 3D issue

### ISSUE THREAD

**Issue by GSavelev-VSEGEI** [minorua/Qgis2threejs#221]
After installing on a new computer the classical issue occured

Neither on LTR 3.10, nor on 3.12.1 not working

![image](https://user-images.githubusercontent.com/57714410/82927986-30211880-9f8a-11ea-8386-94e339d0b29c.png)

**Comment by jukos** [comment]
Hello,
this could help you:
https://github.com/minorua/Qgis2threejs/issues/217

Greetings

**Comment by GSavelev-VSEGEI** [comment]
@jukos I am extremly sorry, but I can't understand how

**Comment by jukos** [comment]
I am not sure, if this is always a solution (also for all qgis versions....), but try this:
1. Open your project
2. close the 3D map view of QGIS
3. exit QGIS
4. start QGIS
5. now try qgis2threejs (NOT start a 3D map view!)

Result?

Greetings

**Comment by GSavelev-VSEGEI** [comment]
@jukos The result of theese actions was posted initially

Now i made some progress on this bug tracking:
I'm working on two machines - one of them is remote desktop and this is how it doesn't work
On my home PC everything works allright.

Do you think rdp is the problem, and how do you think is it possible to solve it?

**Comment by jukos** [comment]
Excuse me please. I don`t know the reason.
I always fighting with 3D problems. I think the programmer oft qgis2threejs and programmers of QGIS 3D must have a communication........If not: We can see the problems.

What you can do, to cry your problems to the world: Open questions within gis.stackexchange to 3D problems. Here you get not always answers......
I also do that.

Greetings

**Comment by GSavelev-VSEGEI** [comment]
Well this might be considered closed, as the rdp was the problemm
