### ISSUE TITLE
qgis2threejs, how to make one layer unsearchable with respect to others that are querable

### ISSUE THREAD

**Issue by macrea** [minorua/Qgis2threejs#228]
Hi, I've been a Qgis cartography user for a few years; lately i have been using qgis2threejs to create 360 ° navigable maps. Now I need to make some layers non-editable compared to others so that the popup does not appear when the mouse is clicked. Can I do it directly in some way on the qgis2threejs export panel or on the html file and how?

I would be grateful for a suggestion

Massimiliano Crea

**Comment by minorua** [comment]
There is `queryable` property for each layer, which is written in scene.json file, but doesn't work in current version. I'll fix it.

**Comment by macrea** [comment]
I get it. Then I await your correction. Thanks
Massimiliano Crea
    Il mercoledì 11 novembre 2020, 03:13:05 CET, Minoru Akagi <notifications@github.com> ha scritto:  
 
 


There is queryable property for each layer, which is written in scene.json file, but doesn't work in current version. I'll fix it.

**Comment by macrea** [comment]
Good evening, I saw you added a code change for "add RayTracingRendering template". Does this also solve the problem of querying layers not working before?
Thanks
Massimiliano Crea
