### ISSUE TITLE
Simple fix for blurry textures

### ISSUE THREAD

**Issue by JocZibret** [minorua/Qgis2threejs#229]
Graphic cards that have the anisotropy setting set to "Application controlled" can display textures in browsers at their max anisotropy.

Add two lines in the Qgis2threejs.js at around 1580+:

      else {    // base64
        var img = new Image();
        var maxAnisotropy = app.renderer.capabilities.getMaxAnisotropy();   //blurry textures fix
        img.onload = function () {
          opt.map.needsUpdate = true;
          _this._loadCompleted(callback);
        };
        img.src = m.image.base64;
        opt.map = new THREE.Texture(img);
        opt.map.anisotropy = maxAnisotropy;   //blurry textures fix		
        defer = true;

**Comment by minorua** [comment]
Implemented in version 2.6. Thanks!
