### ISSUE TITLE
Set output extent based on external image file

### ISSUE THREAD

**Issue by snorfalorpagus** [minorua/Qgis2threejs#24]
Currently the extent of the output threejs model is set to the map canvas extent. This produces the correct output if the "display type" is also map canvas. However, if an external image is used that does not have exactly the same extent as the map canvas the output DEM is misaligned with the texture. Ideally there should be an option to specify that the map extent should come from the external image.

**Comment by CorentinLemaitre** [comment]
Hello, +1 for this old subject
If the user can set the extent mannualy therer is no problem also. If not manualy may be according to a print option
