### ISSUE TITLE
Point cloud problem with Plugin v2.6

### ISSUE THREAD

**Issue by aeduard** [minorua/Qgis2threejs#241]
Potree point cloud is not showing in plugin interface after upgrading to v2.6. Downgrading to v2.5 resolves the problem.

**Comment by aeduard** [comment]
I'm testing once again (QGIS 3.16.12 LTR and Qgis2threejs v2.6 plugin), still having the problem. Point cloud is not visible either in Exporter interface or web page. Does anyone has this issue? Any solution beside downgrading to v2.5?

**Comment by minorua** [comment]
@aeduard Thanks for your report and I'm really sorry for late fix.
