### ISSUE TITLE
[rfc] Upgrade requirement to PyQt 5.15 (matching new releases of QGIS using Qt 5.15.2)

### ISSUE THREAD

**Issue by jgsogo** [minorua/Qgis2threejs#252]
Hi! I've just installed QGIS and this plugin and they are not working together.

I'm running Macos/BigSur with Python 3.9.5, and so far I've tried this combinations:
 * QGIS 3.20 + Qgis2threejs 2.6  🔴 
 * QGIS 3.20 + Qgis2threejs 2.5  🔴 
 * QGIS 3.16 + Qgis2threejs 2.6  🟢 
 * QGIS 3.16 + Qgis2threejs 2.5  🟢  
 
Error raises right after clicking the plugin button in QGis interface, also with an empty project. Error is a segmentation fault, so it can be related to the Qt version. I'm new to these applications,  so I'm not sure where to check the version expected by `Qgis2threejs` and the version provided by `QGIS`. I'll keep investigating, but I wanted to start this post just in case someone can help.

---

Qt version used in QGIS 3.20:

```
⇒  otool -L /Applications/QGIS.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
Frameworks/QtCore.framework/Versions/5/QtCore:
        @rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.15.0, current version 5.15.2)
```

Qt version used in QGIS LTR 3.16:

```
otool -L QGIS-LTR.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore 
QGIS-LTR.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore:
        @rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.14.0, current version 5.14.2)
```

It works with this one 🎉 

Clearly, something changed from 5.14 to 5.15 and the Python wrapper (pyQT) is not compatible with both versions.

**Comment by kannes** [comment]
Is this still an issue, @jgsogo ?

**Comment by jgsogo** [comment]
I can't tell, I haven't tried it again. I'm closing this issue, if I face it again I'll reopen and add any new information. Thanks!
