### ISSUE TITLE
Make the need to copy model files more visible

### ISSUE THREAD

**Issue by kannes** [minorua/Qgis2threejs#254]
When using 3D model files to visualise objects one has to pay attention to copy them after exporting. The export log says so but the messages scroll past quickly and the user might not realise:

![image](https://user-images.githubusercontent.com/7661092/134783591-fdb70ca5-5680-48a4-bcc4-ca1fa1f20812.png)

Only when scrolling up, the warnings are visible:
![image](https://user-images.githubusercontent.com/7661092/134783603-e0e1db59-811e-4e6e-9c60-ad37224f6ee9.png)

It would be great if there was a warning at the bottom of the log, e. g.

```
Export has been completed in 8.01 seconds.
There were warnings for 2 layers, see above.
```

**Comment by minorua** [comment]
@kannes Thanks for your advice. :)

**Comment by kannes** [comment]
Thank you for developing this gem of a plugin so well.
