### ISSUE TITLE
Allow expressions to be used for labeling

### ISSUE THREAD

**Issue by kannes** [minorua/Qgis2threejs#257]
At the moment one can select an attribute to be used for labeling. It would be great if one could use an expression, e. g. to concatenate two attributes or to restrict text to a specific length.

**Comment by stan2345** [comment]
Greetings
Can you please provide a sample expression for the expression dialogue for me to extrude my buildings from one of my attributes in my buildings layer? The new version of the plugin only allows you to add expressions. There is no drop down box to simply select an attribute field with the height values. 
Thanks!

**Comment by kannes** [comment]
The dropdown lists all attributes that are numeric and thus can be used for extrusion. If your attribute is not numeric you need to convert it, e. g. with `to_real("column")` or `to_int("column")`.

**Comment by stan2345** [comment]
That worked!!!

Thanks so much for the quick response!

Take Care

**Comment by Jinger1025** [comment]
> Sorry, where to use these code? I am still can't make sure how to drop down box to simply select an attribute field with the height values. If the expression is needed, could you please give me case how to calculate?
