### ISSUE TITLE
Distance measuring tool

### ISSUE THREAD

**Issue by aeduard** [minorua/Qgis2threejs#259]
A simple distance measurement tools was created together with a friend. It is based on this discussion: [link](https://discourse.threejs.org/t/solved-mesure-distance-between-two-points-on-a-object-by-clicking/6082/23).

If someone wants to use it the following steps should be followed:

1. You have to make the export to web with _3D Viewer with dat-gui panel_ template.
2. Create/download measureTool.js file (remove txt extension), put near index.html: [measureTool.js.txt](https://github.com/minorua/Qgis2threejs/files/7288871/measureTool.js.txt)
3. Add <script src="./measureTool.js"></script> line to head section of the index.html
4. Add the following lines to Qgis2threejs.js after the following block _// get layerId of clicked object_
`        if (typeof measureTool != 'undefined' && measureTool.is_active === true) {
            if (measureTool.initialized === false) {
                measureTool.init(app, Q3D.Config);
            }
            measureTool.setPoint(obj);
        }`

To use it should be activated from dat-gui pane (controls pane) -> Tools group -> Measure distance. Than you have to click on 2 points on the model. The distance will appear as an alert message. While Measure distance tool is checked, it will measure distance between consecutive 2 clicks. Not working with point clouds.

It is tested on EPSG:3844 CRS, with Qgis2threejs v. 2.5 qgis plugin (v2.6 is buggy for me, not relating to this tool).

Any enhancement, feedback is welcome. It would be nice to implement (a refined version) in a future Qgis2threejs version.

**Comment by minorua** [comment]
@aeduard Thanks for your prototype. It encouraged me to go ahead.

**Comment by aeduard** [comment]
@minorua If you need help for testing the plugin before publishing, I would like to get involved. I'm using Qgis2threejs on a regular basis, so it would be pretty convenient for me to do some testing.
