### ISSUE TITLE
Measurement units changed on export

### ISSUE THREAD

**Issue by vovchykbratyk** [minorua/Qgis2threejs#260]
I have a scene in QGIS (terrain and image) that measures around 493 meters by 677 meters.  Everything is projected in UTM (meters).

Everything looks great in Qgis2threejs.

When I export the scene as either glb or gltf, and open it in Blender (also default meters, set to scale factor of 1.0), the measurements totally change.

Blender reports the measurement as approximately 36 meters by 50 meters.

Playing with the base width "sort of" helps, but I do not know how to make it scale properly and can't find anything on the internet about it.

How do I ensure that my measurements stay consistent between projected coordinate system and 3D space?

**Comment by minorua** [comment]
When you set `base width` to the same value as `base extent width`, the units of exported model are same as units of project CRS.

![image](https://user-images.githubusercontent.com/2672095/136504002-3c4c3caf-09d4-4e1f-81cc-ec8a01ca316e.png)

**Comment by minorua** [comment]
`Origin of xy-plane` setting is added to scene settings dialog in version 2.7. Thanks!
