### ISSUE TITLE
How to render multiple raster layers to a DEM

### ISSUE THREAD

**Issue by GeoPontes** [minorua/Qgis2threejs#265]

**Comment by GeoPontes** [comment]
Hey guys!

First, thanks creating and maintaning this amazing tool. Secondly, I'd like to know if anyone could point me to the correct configuration to render multiple raster layers, with respect to only one (raster) DEM base layer (3D model). 

Long history short, I have multiple raster layers, and also some vector layers (which are not necessararaly important for this topic); they correspond to: a) elevation data (not styled, base raster layer); b) hipsometric data (styled, sencundary raster layer); c) bathymetric data (styled raster layer and secondary); c) land use classification data, from 2019 (styled raster layer and secondary); and e) land use classification data, from 1985 (styled raster layer and secondary).

What I'd like to accomplish is the following: from a base raster layer, which will be the base for the 3D model (i.e., DEM), I want to be able to change layers visibility. This aim relates to the possbility of a web user be able to see either the stacked data or individual layers, by simply alternating beetween layer visibility on web application. 

Is it possible to accomplish this with QGIS2threejs ? I think that I may be doing a mislead configuration with the raster layers, due to the fact that with vector layers, I'm able to perform this same objective.

Any hints? Figures are for ilustrate what I'm facing.

![Captura de Tela (18)](https://user-images.githubusercontent.com/57741984/144911279-d9f0c11c-e7b3-467d-b542-715bb54ec840.png)
![Captura de Tela (16)](https://user-images.githubusercontent.com/57741984/144911283-d860eca5-cba8-4776-b4da-95a340f57aa3.png)
![Captura de Tela (17)](https://user-images.githubusercontent.com/57741984/144911287-401c9924-855e-4e7c-9c8f-8a8e5f03bbd1.png)


Thanks

**Comment by minorua** [comment]
This feature is planned in development for 2.7 and I'm working on this feature now. Thanks.

https://github.com/minorua/Qgis2threejs/projects/4

**Comment by GeoPontes** [comment]
Great! I'm looking forward to this new version! Thanks for the answer.
