### ISSUE TITLE
3D visualization drillhole data using Geoscience plugin

### ISSUE THREAD

**Issue by ems1995** [minorua/Qgis2threejs#277]
Tested the geoscience plugin in combination with Qgis2threejs to visualize drillhole data in 3D. 

I got the error message: 'QTabWidget' object has no attribute 'setTabVisible' when activating the polyline layer (drillhole paths)

I added LayerType.LINESTRING  to line 886 of proppages.py, which seems to have resolved the issue.
 
hasRPt = (layer.type in (LayerType.POINT, LayerType.POLYGON, LayerType.LINESTRING))

**Comment by minorua** [comment]
Thanks!
