### ISSUE TITLE
Transparency of DEM layers not working, plugin version 2.7

### ISSUE THREAD

**Issue by aeduard** [minorua/Qgis2threejs#280]
The interactive transparency slider for DEM layers within dat-gui panel is not working. If transparency is set in qgis plugin it is displayed on browser, but won't recognize it's setting and can't be modified.

Using:
QGIS 3.16
QGIS2THREEJS version: 2.7
Browser: Firefox, Opera, Chrome

**Comment by aeduard** [comment]
Initially I've encountered the bug when I've updated an existing model to v2.7. After seeing that you couldn't reproduce, I've tested with a completely new file/scene. Transparency for DEM worked, but when I've tried to limit it's extent with **Clip DEM with polygon extent**, it stopped working. If needed I can post some screenshots, or share a demo project.

**Comment by minorua** [comment]
Thanks for your bug report.
