### ISSUE TITLE
No puedo representar capas vectoriales (líneas) en Qgis2threejs

### ISSUE THREAD

**Issue by Juanjo1969** [minorua/Qgis2threejs#281]
Buenos días.

Con la nueva versión del complemento (2.7), no puedo representar capas vectoriales lineales, no me permite la apertura de las propiedades de la capa para configurarla. Sí puedo representar capas de puntos y polígonos. Con la versión anterior si podía representar las capas vectoriales de líneas.

Si trato de abrir el menú Propiedades... en la ventana de canvas, me sale error:
2022-04-06T07:32:00     WARNING    Error de Python : Ha ocurrido un error mientras se ejecutaba el código de Python: Vea el registro de mensajes (Error de Python) para más detalles. Incrusto la pila de errores para mas información.

[Pila de errores.pdf](https://github.com/minorua/Qgis2threejs/files/8423957/Pila.de.errores.pdf)

[Capa vectorial.pdf](https://github.com/minorua/Qgis2threejs/files/8424012/Capa.vectorial.pdf)

Tengo la versión 3.10 La Coruña de QGIS.

Saludos y muchas gracias.

**Comment by minorua** [comment]
Thanks for letting me know the bug. Gracias.
