### ISSUE TITLE
Point layer type "Icon" does not appear anymore in the type box and it was replaced by "billboard"

### ISSUE THREAD

**Issue by cjpascoa** [minorua/Qgis2threejs#295]
v2.7.1

Hi, I had Qgis2threejs setup to work with icon files inside Point layers.
In this version the type "Icon" does not appear anymore in the type box and it was replaced by "billboard" which cannot link to a file.
The documentation still has the "Icon" type.
What might be the cause?
I am using QGIS 3.16.14 but I checked with QGIS 3.22.8 with the same result.
Thank you for your help.

Carlos

**Comment by minorua** [comment]
Thanks for letting me know. There are actually still many other things to edit.
