### ISSUE TITLE
Vertical holes not plotting

### ISSUE THREAD

**Issue by grantboxer** [minorua/Qgis2threejs#326]
I am trying to display a set of drill holes, both angled and vertical. The 3D coordinates have been produced using the Geoscience plug-in. I feel this used to work OK, but the current version 2.7.2 doesn't appear to display the vertical holes, only the angled holes. Can I roll back to an earlier version to check if a gremlin has got into the code?
I am running QGIS v 3.34.

**Comment by minorua** [comment]
Older plugin versions can be downloaded from the [plugin page on QGIS Python plugin repository website](https://plugins.qgis.org/plugins/Qgis2threejs/). You can install a downloaded zip file using plugin manager (See [docs](https://docs.qgis.org/3.28/en/docs/user_manual/plugins/plugins.html#the-install-from-zip-tab)).

**Comment by grantboxer** [comment]
Ah yes, many thanks!

 

Cheers Grant

**Comment by grantboxer** [comment]
I installed version 2.7.1 and the vertical hole plotting works. Not sure what has changed for version 2.7.2. Over to you!

**Comment by minorua** [comment]
The following message is logged in the log panel:

`Invalid geometry skipped: line — vertical`

This is a bug caused by [the fix](cc32e8c1) to #298.

@grantboxer Thank you very much for your report.
