### ISSUE TITLE
[No 3D objects were rendered? There is a compatibility issue with QGIS 3D view...]

### ISSUE THREAD

**Issue by jpdeglet69** [minorua/Qgis2threejs#339]
Hello,

Issue or? in an existing project.

Error : No 3D objects were rendered? There is a compatibility issue with QGIS 3D view. You need to close QGIS 3D view(s) and restart QGIS to use this preview.

but I don't and never defined/used QGIS 3D views in this project.

It was running fine a couple of days...
- Actual configuration: Mac OS v13.6.6 / QGIS v3.36.1 / Qgis2threejs v2.7.3

The Qgis2threejs re-installation doesn't solved the issue.

A lot of WebGL/Java Errors see screenshot attached.
<img width="1024" alt="Capture d’écran 2024-04-18 à 13 06 48" src="https://github.com/minorua/Qgis2threejs/assets/36116259/a2c9246c-928c-4cfc-8c39-5c44b8f1320f">

So???

**Comment by jlpoolen** [comment]
I've had problems, too, and get the type of errors you show when loading GeoTIFF from USGS (United States Geological Survey).  I went a step further and proceeded with an export which occurred.  Then I submitted two of the image files, i.e. test_export_gLTF.gltf, generated from the Qgis2Three plugin to Don McCurdy's site at https://gltf-viewer.donmccurdy.com/ and got these type of errors/warnings:

at https://gltf-viewer.donmccurdy.com/
attempt to view:

```
/home/jlpoole/qgis/3DExport_Apr_16_2024/test_export_gLTF.gltf

resulted in a black screen

When I clicked the errors icon at bottom left, this page:


Validation report

    Format: glTF 2.0
    Generator: THREE.GLTFExporter
    Stats:
        11 draw calls
        0 animations
        7 materials
        208182 vertices
        411360 triangles
    Extensions:
        None

Report generated byKhronosGroup/glTF-Validator 2.0.0-dev.3.9.
Error	Message	Pointer
ARRAY_TYPE_MISMATCH	Type mismatch. Array element null is not a 'number'.	/accessors/4/min
ARRAY_TYPE_MISMATCH	Type mismatch. Array element null is not a 'number'.	/accessors/4/max
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/5/primitives/0/attributes/POSITION
ACCESSOR_INVALID_FLOAT	Accessor element at index 2 is NaN.	/accessors/4
ACCESSOR_INVALID_FLOAT	Accessor element at index 5 is NaN.	/accessors/4
ACCESSOR_INVALID_FLOAT	Accessor element at index 8 is NaN.	/accessors/4
ACCESSOR_INVALID_FLOAT	Accessor element at index 11 is NaN.	/accessors/4
ACCESSOR_INVALID_FLOAT	Accessor element at index 14 is NaN.	/accessors/4
ACCESSOR_INVALID_FLOAT	Accessor element at index 17 is NaN.	/accessors/4
ACCESSOR_INVALID_FLOAT	Accessor element at index 20 is NaN.	/accessors/4
Info	Message	Pointer
UNUSED_OBJECT	This object may be unused.	/meshes/0/primitives/0/attributes/TEXCOORD_0
UNUSED_OBJECT	This object may be unused.	/meshes/1/primitives/0/attributes/TEXCOORD_0
UNUSED_OBJECT	This object may be unused.	/meshes/2/primitives/0/attributes/TEXCOORD_0
UNUSED_OBJECT	This object may be unused.	/meshes/3/primitives/0/attributes/TEXCOORD_0
UNUSED_OBJECT	This object may be unused.	/meshes/4/primitives/0/attributes/TEXCOORD_0
IMAGE_NPOT_DIMENSIONS	Image has non-power-of-two dimensions: 1024x951.	/images/0
IMAGE_NPOT_DIMENSIONS	Image has non-power-of-two dimensions: 1024x951.	/images/1
IMAGE_NPOT_DIMENSIONS	Image has non-power-of-two dimensions: 1024x951.	/images/2
IMAGE_NPOT_DIMENSIONS	Image has non-power-of-two dimensions: 1024x951.	/images/3
IMAGE_NPOT_DIMENSIONS	Image has non-power-of-two dimensions: 1024x951.	/images/4
```
Unfortunately, I do not possess enough knowledge at this time about gLTF to know if these are fatal errors or not.  I am troubled by the "IMAGE_NPOT_DIMENSIONS" errors which may be caused by my selecting a smaller area to export which perhaps is suppose to have a "power-of-two" dimension?

**Comment by StefanKaiser-TomTom** [comment]
duplicate? https://github.com/minorua/Qgis2threejs/issues/222

**Comment by RJbalikian** [comment]
I got this same error. When I followed the error log, I got a python error (changed the file path so as not to include my username, etc.:

2024-09-16T11:19:11     WARNING    Traceback (most recent call last):
              File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\user/python/plugins\Qgis2threejs\q3dwindow.py", line 465, in pluginSettings
              dialog = SettingsDialog(self)
              ^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\user/python/plugins\Qgis2threejs\pluginsettings.py", line 47, in __init__
              parser = configparser.SafeConfigParser()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
             
When I follow the python file, it seems that the SafeConfigParser is only available for python versions less than 3.12. I don't know the details of which python versions get installed with which QGIS versions...but perhaps this plugin will not work with any QGIS version that uses a python version 3.12 or greater?

**Comment by minorua** [comment]
@RJbalikian See https://github.com/minorua/Qgis2threejs/issues/345.

**Comment by minorua** [comment]
See https://github.com/minorua/Qgis2threejs/issues/358#issuecomment-2415558196.

Thank you for your feedback.
