### ISSUE TITLE
Extrusion height ratio

### ISSUE THREAD

**Issue by camillemonchicourt** [minorua/Qgis2threejs#34]
When we are on a wide area, the extrusion ratio is good : 

![3dlarge](https://cloud.githubusercontent.com/assets/4418840/5536423/8219cb32-8a91-11e4-9acd-e982dd30f836.jpg)

But when we are aon a small area (under scale 1:5000 as an examples), the ratio is too high : 

![3dserre](https://cloud.githubusercontent.com/assets/4418840/5536427/a54a8376-8a91-11e4-9b11-a9092b27d474.jpg)

Would it be possible to be able to fix this ratio as a setting or it could be a fixed pourcent of the scale ?

Thanks.

**Comment by pcav** [comment]
Could this be closed? Or transformed into a feature req (add an auto-adjusting function)?
