### ISSUE TITLE
Pipe w/o spheres at vertices

### ISSUE THREAD

**Issue by vabufano** [minorua/Qgis2threejs#341]
Hi,
I would like to know if it is possible to display a 'line layer' in 'pipe' version without the spheres placed at the vertices but only with the cylinders.

**Comment by minorua** [comment]
You can use Processing Toolbox > Explode lines to split each linestring into separate segments with no intermediate vertices.

https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#explode-lines
