### ISSUE TITLE
Using Icon for point error(Python)

### ISSUE THREAD

**Issue by Oneil974** [minorua/Qgis2threejs#37]
Hi,

When i  choose icon for point rendering, I get a python error at about 30% of the export.

For me icon parameter doesn't work on Linux or on windows 7.

Thank a lot for this very amazing plugin and for your work.

![captureqgis2threejs](https://cloud.githubusercontent.com/assets/11059074/6247117/0c41e68a-b78a-11e4-9b5a-874478aea18d.PNG)

**Comment by minorua** [comment]
confirmed.

**Comment by Oneil974** [comment]
Thank,

Very good work it works like a charm.
