### ISSUE TITLE
Extrude vector data options greyed out.

### ISSUE THREAD

**Issue by nickislander** [minorua/Qgis2threejs#41]
Hi, For some reason my option to extrude any vector data is greyed out. I can manipulate and export raster data. I've tried a variety of datasets, coordinate systems, plugin reinstalls, different qgis versions, but its always greyed out. Any ideas?

![vector_qgis2three](https://cloud.githubusercontent.com/assets/9062919/7486269/6535142c-f37d-11e4-9e47-c116e1304ec6.PNG)

**Comment by nickislander** [comment]
Just discovered there is a checkbox. Unbelievable. I figured it was just my polygon symbol (which was also grey) until I clicked around wildly in frustration and turned this little sucker on.

![checkbox](https://cloud.githubusercontent.com/assets/9062919/7491984/aea3f028-f3c9-11e4-8ca9-16283d69dee2.JPG)

**Comment by ethomas33** [comment]
Wow, I just spent the better part of an afternoon trying to solve this, thank you!
