### ISSUE TITLE
how to Auto Rotate On / Off with a Android Web browser

### ISSUE THREAD

**Issue by jancelin** [minorua/Qgis2threejs#44]
hi.
Is it possible to Auto Rotate On / Off with  a Android Web browser, please?

**Comment by minorua** [comment]
Not impossible. Focus an inputable text box (e.g. current view url in the about (help) box), then type `r`.

However, UI should be improved for tablet devices. Maybe command menu should be added to the dat-gui panel.

**Comment by jancelin** [comment]
Working . thanks

**Comment by minorua** [comment]
Auto rotation command has been added to the dat-gui panel in 21b8e13 (which can be used with touch screen devices).

**Comment by jancelin** [comment]
Great, thanks
