### ISSUE TITLE
Southern Hemisphere shadows

### ISSUE THREAD

**Issue by iantidy-ncc** [minorua/Qgis2threejs#45]
I notice that the sun angle seems to be wrong for the southern hemisphere.  The shaded parts of the buildings seem to be the northern facing sides instead of the southern faces.

Is there a way to set the sun azimuth and angle (or position relative to the map canvas) and also obey rules around hemispheres.

Thanks.

**Comment by minorua** [comment]
Currently, there are no setting items on the GUI, but you can do that by editing azimuth and altitude angle at [Qgis2threejs.js Line 12-13](https://github.com/minorua/Qgis2threejs/blob/master/js/Qgis2threejs.js#L12). Or just try rotating the map canvas.

**Comment by iantidy-ncc** [comment]
That has fixed the problem.  Thanks
