### ISSUE TITLE
[feature request] export to OBJ file format

### ISSUE THREAD

**Issue by kampfgnu** [minorua/Qgis2threejs#47]
hi,
first of all, thanks for the plugin!

i modified the exported file "Qgis2threejs.js" to generate an OBJ file of the model, to import it into 3D modelling software. iterating through the three.js PlaneBufferGeometry's vertices and faces to create a string (https://gist.github.com/kampfgnu/80a18f73f4212a12da5b) that i store in a local file.

it would be cool being able to export the obj file directly from QGIS! :)

cheers

**Comment by minorua** [comment]
There is `Wavefront (.obj)` button to save the model to OBJ file in the FileExport template. https://github.com/minorua/Qgis2threejs/wiki/ExportSettings#-template
![image](https://cloud.githubusercontent.com/assets/2672095/9560008/dd71bf12-4e3b-11e5-961a-0a939972ab00.png)
Try it!

It uses web browser to save the model to obj file. Yes, that's not direct way, but it might be possible to export directly by communicating the export page with QWebView in the future.

**Comment by kampfgnu** [comment]
oh sorry, i didn't recognize the template file select in the export dialog.
that's exactly what i need, thanks very much!
cheers!

**Comment by ainthek** [comment]
Is this still possible with current version ?

**Comment by minorua** [comment]
> Is this still possible with current version ?

No, plugin version 2.x can save 3D model only in glTF (.glTF/.glb) format.

You can convert a glTF file to an OBJ file with 3D builder in Windows 10.
