### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by oldgit8** [minorua/Qgis2threejs#49]
Thanks for a great plug-in!  My first project works fine with Chrome and Firefox on windoze, but not with either browser on an Android 5.1 tablet.

Firefox: Unresponsive script http://pkhbc.x10.mx/tongfarm/threejs/three.min.js:433 (or 437 or some other number). On continue: background and controls only shown.
Chrome: Rats! WebGL hit a snag.  On ignore: controls only shown (eventually!)

FF will show undulating monkey OK, Chrome will not (with no Rats! message).

Is there some setting I'm missing?

**Comment by minorua** [comment]
I don't have any Android tablets that support WebGL (My iPad2 (iOS 8.4.1) is able to work if the exported data is not too large).
Please make sure that your tablet and the web browsers support WebGL at http://get.webgl.org/
Next, try an export with small data, without JSON/COLLADA models.

**Comment by minorua** [comment]
Try [demos](https://github.com/minorua/Qgis2threejs/wiki/Demos).

**Comment by oldgit8** [comment]
Thanks for the quick reply.  The demos work for me in FF, except I can't figure out how to zoom consistently. It is way too sensitive to small gestures and quickly disappears in the middle of the screen and cannot be recovered.

I don't know what a JSON/COLLADA model is - I'm just using your plug-in with no knowledge of threejs.

How large is too large?  Can you see my model at pkhbc.x10.mx/tongfarm/? The main .js file is 5MB, one layer has 2000 polygons.

**Comment by oldgit8** [comment]
Update: all demos work fine on Chrome on the tablet.  The zooming issue must be just FF.

**Comment by minorua** [comment]
> How large is too large? Can you see my model at pkhbc.x10.mx/tongfarm/? The main .js file is 5MB, one layer has 2000 polygons.

I can see your models on my PC, but the data size of the models is too large for my iPad2 : (.

**Comment by oldgit8** [comment]
Excellent, thanks, at least I know what to do!

**Comment by juned393** [comment]
Solution is bit tricky...
You can solve webgl hit a snag problem by enabling Hardware Acceleration When Available.
Method to enable Hardware Acceleration is as below:
1. Open setting in chrome.
2. Click on left topmost three dots and then Click on Settings.
OR
   Simply Enter URL chrome://settings in new tab.
3. Scroll down to show advanced settings
4. Now scroll down and just tick mark Use Hardware Acceleration When Available
5. Now simply restart chrome and it will solve your WebGL problem
This is one method to solve WebGL Hit a snag error, you can refer other method from below source.
Source: [webgl hit a snag](https://wildtricks.com/webgl-hit-a-snag-solved/)
