### ISSUE TITLE
Vertical exaggeration = 1

### ISSUE THREAD

**Issue by githubnagib** [minorua/Qgis2threejs#52]
Hello,
How do I set Vertical exaggeration is equal to 1.
When I export a DEM file with Qgis2threejs plugin, it seems to me that the ground is somewhat elongated

**Comment by minorua** [comment]
Both horizontal and vertical units of CRS of DEM are meters? If not, you need to project the DEM to a projected CRS (e.g. UTM).

**Comment by githubnagib** [comment]
This is my projection :
PROJCS["Transverse_Mercator",GEOGCS["GCS_Geographic Coordinate System",DATUM["D_HKOGEL",SPHEROID["Bessel_1841",6377397.155,299.1528131060786]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["scale_factor",0.9999],PARAMETER["central_meridian",18],PARAMETER["latitude_of_origin",0],PARAMETER["false_easting",6500000],PARAMETER["false_northing",0],UNIT["Meter",1]]

**Comment by minorua** [comment]
Please select "World" in the tree view on the left side of the dialog. An edit box to set the vertical exaggeration is displayed on the right side.

**Comment by githubnagib** [comment]
Thanks
