### ISSUE TITLE
QGIS - QGIS2threejs Mapping out 3D points with GPS

### ISSUE THREAD

**Issue by JolyDroneSP** [minorua/Qgis2threejs#56]
My GPS reads Latitude, Longtitude and Altitude from sea level. However, when I try to use qgis2threejs to specify the Altitude like so:

![](http://i.stack.imgur.com/UdMWT.png)

The output I get is like so:

![](http://i.stack.imgur.com/12nBD.png)

Even though the reading was taken from ground level...

I believe the reason for this is because of how the Z-Coordinates are calculated when I specify my own Z-Coordinate values - by adding "Relative to DEM" + "Altitude" + Addend.

 Is there anyway to remove the "Relative to DEM" addition?

**Comment by minorua** [comment]
"Altitude" under the "Absolute value" should work.

**Comment by JolyDroneSP** [comment]
@minorua I got the results I wanted for now. Thanks!
