### ISSUE TITLE
Live Exporter (3D Viewer)

### ISSUE THREAD

**Issue by minorua** [minorua/Qgis2threejs#61]
If once QGIS has moved to Qt5/PyQt5 (and Python3)...

We can do something like this!

![q3dviewer](https://cloud.githubusercontent.com/assets/2672095/13164423/6ce9a480-d6f8-11e5-8343-d030789b642c.gif)
Image was created with GSI Tiles (std, relief, ort and dem).

Available on `dev` branch. Being developed using socket connection for now. In Ubuntu, `python3-pyqt5.qtwebkit` package and its dependencies need to be installed.

**Comment by lucacasagrande** [comment]
Great! :+1:

**Comment by minorua** [comment]
Thank you, Luca!
I will welcome your participation in the development after the first release ; ).

**Comment by Epycart** [comment]
Wonderful !

**Comment by minorua** [comment]
Almost done. Will be released in next week.
