### ISSUE TITLE
Save image in higher resolution - Result image is crop

### ISSUE THREAD

**Issue by Epycart** [minorua/Qgis2threejs#68]
Hello,
First of all, thanks for that usefull plugin.
I wish to "save as image" in my browser. If possible in high resolution.
But when I put an higher resolution (5000x3000) than the default one, the result image is crop to only a part of what appears on my screen. That result image match the default resolution.
I work on Mac OS 10.11.2 whith firefox 45.0.
Is it a bug or a wrong use ?
Have a nice day.

**Comment by fnorf** [comment]
Could you elaborate how you "save as image" in your browser? Are you doing that with a Firefox plugin?

**Comment by minorua** [comment]
Duplicate of #42
