### ISSUE TITLE
Copyright decorations not appearing in map canvas output

### ISSUE THREAD

**Issue by stevefaeembra** [minorua/Qgis2threejs#69]
Not sure whether this worked before or not. 

I'm using the Copyright data decoration to provide attribution - it doesn't seem to be included when I use **Map Canvas Image** option (max. resampling setting, 400% raster resolution). Also seems to affect other decorators  like north arrow and scale bars. Not a major problem as I can edit the HTML output for the attribution.

Plugin version 1.4, Windows 10 64bit, QGIS 2.14.2, FF Browser

**Comment by minorua** [comment]
PyQGIS doesn't seem to support drawing decorative things. So we need to render them by this plugin itself (or using a plugin layer).

Workaround for a while:
1. Prepare a very large display. ;-)
2. Expand the QGIS window greatly.
3. Save the canvas image to a PNG file.
(Keep the window size...)
4. Open the PNG file in a graphics editor, and draw a label in proper size on the image.
5. Select the PNG file in the `Display type` option, and then do export.

**Comment by minorua** [comment]
Use footer label to give attribution.
