### ISSUE TITLE
Error when multiline label

### ISSUE THREAD

**Issue by Jorishin** [minorua/Qgis2threejs#72]
Hello,
The plugin does not work when I check "export attributes" in a shape layer with multiline data. I tried to create a multiline label (as it is nog possible within the plugin) by creating a property that contains a line feed.

ASSE 
 638 inw/km2
- 1.038 %

When "export attributes" is not checked, all works well.
the project can be downloaded here:
https://dl.dropboxusercontent.com/u/23700421/consolid.zip

**Comment by minorua** [comment]
Use `<br>` instead of line feed.
