### ISSUE TITLE
Attributes of sphere with zero radius exported

### ISSUE THREAD

**Issue by PanierAvide** [minorua/Qgis2threejs#73]
Hello,
In `point_basic.py`, when a sphere has a zero radius, it is not exported. However, in `export.py`, the attributes of features are always exported. This causes in JS result that `lyr.f`is called with an out of bounds index, making the data not appearing. A fix making attributes of zero radius sphere being not exported, or exporting a sphere with a minimal size, will fix the issue.
Cordially.

**Comment by minorua** [comment]
Thanks for the report!
