### ISSUE TITLE
Sphere Radius might be Diameter?

### ISSUE THREAD

**Issue by fnorf** [minorua/Qgis2threejs#82]
Following https://gis.stackexchange.com/questions/210334/qgis-plugin-qgis2threejs-3d-object-size-scale-incorrect I assume that the Radius field for a Sphere object actually sets its diameter. I have not tested it (yet), just wanted to make a note of it here.

**Comment by minorua** [comment]
That is radius, not diameter. It seems that vertical exaggeration (default is 1.5) complicates things. I would like to change the default value to 1.

**Comment by fnorf** [comment]
Oh, duh! :) Would definitely be a good idea to default to 1. Maybe the values for non-DEM 3D objects could have a "exaggeration free mode" as well?

**Comment by minorua** [comment]
Now the default value is 1.
