### ISSUE TITLE
Export multiple textures

### ISSUE THREAD

**Issue by qmenen** [minorua/Qgis2threejs#86]
Would it be posible to include layers initially disabled (not visible), activable, a posteriori, from the Control Panel?
Would it be posible to render more than one raster layer (ortophoto and topographic, for example), activable/desactivable from the control panel?

**Comment by minorua** [comment]
Impossible in current version, but these features would be possible to be added in the future.

**Comment by qmenen** [comment]
Thank you, Minorua, for your prompt and positive response,

Implement such improvements I think it would be a huge boost to the project. Although, made to order ;-), the option of using different typefaces for labeling of maps and display them in relation to the scale would help much in what, in my view, is the weakest Plugin point when it comes to topographic maps .

I have devoted some time to it, but my programming skills are not enough. If you have any suggestions that might help me unravel your extraordinarily synthetic development would be extremely pleased to bring my experience to the project.

I attached some links to my latest tests. but does not seem to work. My land, Asturias (Northern Spain), has an intricate relief (Alpine orogeny), topped with a close karstic massif 3,000 m just ten kilometers from the sea: the National Park Picos de Europa, whose link I included . It is therefore ideal for modeling territory. And an example of the problems pointed out.

(I do not make the reference to the plugin, the Qgis or threejs. As I noted in my previous posts, I am still in the testing phase and do not want to hold anyone of my errors. As we begin marketing, they will be in their rightful place.)

www.cian.com/Proyecto/ElAlba1.html       (Res: 100%, 9 MB)
www.cian.com/Proyecto/Artedo2.html      (Res: 200%, 21 MB)
www.cian.com/Proyecto/Torimbia4.html   (Res: 400%, 54 MB)
www.cian.com/Proyecto/Picos1.html         (Res. 100%, 15 MB, example serving as a model for my Typographical requests. The text on the canvas, especially in hilly territory, is deformed and is not well suited at different scales. On the other hand, mobile text input is clouding the screen. If I could be hidden at the start and turned on / off at an appropriate time ... or if viewing could be linked to the scale ... ;-)

Best regards

**Comment by minorua** [comment]
implemented

**Comment by amr66** [comment]
Is there any progress on that feature? I'm really interested in switching textures. May be there's a workaround?

**Comment by chianhenglee** [comment]
Is there any progress on this? Would love to see this function implemented.
