### ISSUE TITLE
Layering of labels 

### ISSUE THREAD

**Issue by JasonDalton** [minorua/Qgis2threejs#89]
It would often help the readability of labels if the labels could optionally be placed in 3D rather than a 2D projection.   This GIF shows how when I navigate through my output, I can't really tell which label goes with each object.  If they were in 3D space, then at least the ones behind would be occluded, and their relative size would give visual clues to the object each label is attached to.
![3dlabels](https://cloud.githubusercontent.com/assets/2123913/22120345/63cf9a00-de4d-11e6-9e92-eb2db415e3e5.gif)

**Comment by minorua** [comment]
@JasonDalton Thanks for your advice!
