### ISSUE TITLE
Did Anyone Faced The Problem Of Screen Overlay Detected?

### ISSUE THREAD

**Issue by juned393** [minorua/Qgis2threejs#93]
Problem Solved...

Turn Off Screen Overlay By Following settings:
1.Settings
2.Apps
3.Option(Three Dots)
4.Click on “Draw Over Other Apps” OR “App Can Appear on Top” whichever option available in your device…
5.Now list of apps whose screen overlay is enabled will appear…
6.Disable /Turn Off For All App…

Then Your Problem Must Be Solved…
Source: [Screen Overlay Detected](https://wildtricks.com/screen-overlay-detected-solve-problem-android-device/)

**Comment by minorua** [comment]
@kannes Thanks.

**Comment by kannes** [comment]
Best even delete it or remove their link, then their spam attempt is gone. :)
