### ISSUE TITLE
3D polygon not rendered correctly

### ISSUE THREAD

**Issue by JoSchoey** [minorua/Qgis2threejs#94]
Sometimes when rendering 3D extruded polygons, the top and bottom surfaces do not render properly, as shown in the images.  Every once. in a while it works properly, and sometimes the missing parts are in different places.  Any advice on what I am doing wrong? QGIS v2.16
![polygon problem1](https://cloud.githubusercontent.com/assets/26586963/24178809/d25bf9a0-0e81-11e7-92e7-df93e5100c40.png)
![polygon problem](https://cloud.githubusercontent.com/assets/26586963/24178810/d2620a70-0e81-11e7-9ade-82c2eb429c6e.png)

**Comment by DigDigDig** [comment]
How are you loading this layer in?  Is it a JSON/Collada model or an extrusion of a polygon?  

My thought is that you probably have extra vertices in your shape that is clipping the inside of the polygon.

**Comment by minorua** [comment]
@JoSchoey Please attach your polygon data file if you can.

**Comment by minorua** [comment]
Please reopen if the issue still remains.
