### ISSUE TITLE
Panning functionality

### ISSUE THREAD

**Issue by pskrivanos** [minorua/Qgis2threejs#95]
Hello, 
Just wondering how difficult it would be to add panning functionality to Qgis2threejs. I love the current features but think it would be great if the user could pan around the map in addition to zooming and rotating the view. 

Thanks
P.S. I am not a programmer....

**Comment by minorua** [comment]
Hit `i` key in the 3D viewer to display small mouse/key control guide.

In case of OrbitControls:
> Mouse
> Left button + Move : Orbit
> Middle button + Move : Zoom
> Right button + Move : Pan
>
> Keys
> ...

**Comment by pskrivanos** [comment]
Terrific, thanks and can't believe I missed that. Is there also a way to pan on an iPhone toughscreen?

**Comment by pskrivanos** [comment]
Actually just realized that I can use three fingers to pan. Thank very very much for all your help!
