### ISSUE TITLE
Compatibility with ThreeJS r85

### ISSUE THREAD

**Issue by DigDigDig** [minorua/Qgis2threejs#97]
In an effort to speed up performance I did a little work to bring the existing Qgis2threejs.js file up to date with the current release of Three.js (r85).

The big problem that I was hitting had to do with the way in which the system was triangulating polygons.  Moving to r71 showed me a warning that there were errors triangulating my polygons, duplicate points, etc.

I discovered that Three.js needs points to be loaded in clockwise and that loading them in counterclockwise can result in these errors.  

To get around this without a heavy rewrite I implemented [Earcut.js](https://github.com/mapbox/earcut) as [described here](https://github.com/mrdoob/three.js/issues/5959).   You can see an implementation of this [here](https://threejs.org/examples/webgl_geometry_text_earcut.html#00D8FF111#Earcut).

In the above example the triangulation function was renamed `THREE.ShapeUtils.triangulateShape` instead of `THREE.Shape.Utils.triangulateShape`.  I had to go into qgis2threejs.js and change that line to match.  It won't work the other way around.

The only other thing that I needed to do was to comment out a few lines referencing the ambient property of a material.  This did the trick and now I have a version that loads much faster than the current build.

I am having a problem where large planes are causing rendering slowdowns. The same model was rendering just fine with r70 and the standard triangulation.  I'm not sure if that is due to earcut, or r85.  I'll be experimenting.

**Comment by DigDigDig** [comment]
Just ran a quick performance check.  Looks like the r85 earcut test is loading more efficiently overall, with the biggest improvements in scripting and painting.  

There are slowdowns in losses that stem from the resizing of DEM textures.  If this resizing could get handled as the texture data is loaded into the image utility then we could skip this step and improve performance again.  

![r70profile](https://cloud.githubusercontent.com/assets/17930616/25342857/55d7efc8-28db-11e7-9a09-4b6b4aac02e3.jpg)

![r85profile](https://cloud.githubusercontent.com/assets/17930616/25342863/594c27be-28db-11e7-8fd4-10ce27adc368.jpg)

**Comment by minorua** [comment]
Thanks for sharing the information!
