### ISSUE TITLE
Modification to change the orbital center

### ISSUE THREAD

**Issue by AntoninMazoyer** [minorua/Qgis2threejs#98]
We modified Qgis2threejs.js in order to change the orbital center by clicking on the model. It allow to wiew better and move easily in the model when you're viewing an area far from the initial center.

The change is at the line 587 of Qgis2threejs.js by adding:
app.controls.target.set(point.x, point.y, point.z);

I think it will be good to add this modification in the next version of the plugin

Cheers

**Comment by minorua** [comment]
`Zoom in here` button was added to popup opened on click.
