### ISSUE TITLE
Point Elevation Offset in Popup Attribute Table

### ISSUE THREAD

**Issue by DigDigDig** [minorua/Qgis2threejs#99]
When clicking a point object (sphere, disk, etc.) that has been offset from the base DEM, the popup attribute table reads a lat, lon, and elevation for that point.  The Lat/Lon read fine, but the elevation readout displays the elevation of the query marker, instead of the elevation of the point on the DEM.  This is problematic because the point objects are always offset from the DEM so that they are visible.  When clicking on the point, I don't care about the virtual elevation of its maker, I want to know the elevation of the location that it references on the DEM below it.

Is there a way that I can subtract the offset value of my points to arrive back at the actual height of the DEM below them?

I've attached a screengrab below to illustrate what I'm talking about.  I'm dealing with seafloor here so elevation has been changed to depth.  The depth scalebar is a placeholder so just ignore that.

![elevationoffset](https://cloud.githubusercontent.com/assets/17930616/26641975/2ef6f73c-45fa-11e7-83b8-e65f57f6fe99.jpg)

**Comment by minorua** [comment]
You can use _DEMLayer.getZ()_ to get the elevation of the DEM under the clicked point.
For example,
```
// app.showQueryResult = function (point, layerId, featureId) {
...

var demLayer = app.project.layers[0];
var z = demLayer.getZ(point.x, point.y);
var pt = app.project.toMapCoordinates(point.x, point.y, z);

...
// };
```

**Comment by DigDigDig** [comment]
Thank you for the fast response Minorua.  That worked like a charm!
